from aoc.puzzle import Part1

class PuzzlePart1(Part1):
    def solve(self, input_str: str):
        """
        antinodes occur at any point two antennas are in line with same freq when on eantenna is more than twice away
        :param input_str:
        :return:
        """
        map = [line.strip() for line in input_str.strip().splitlines()]
        pass

if __name__ == '__main__':
    puzzle = PuzzlePart1(2024, 8)

    example_input = '''
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
    '''

    assert 14 == puzzle.solve(example_input)

    # answer = puzzle.solve(puzzle.input())
    # print(f'answer: {answer}')
    # assert None == answer
